version: '3.8'

services:
  go-user-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - "8088:8088"
    networks:
      - network_user_service

  mysqldb:
    env_file: .env
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - network_user_service

networks:
  network_user_service:
    driver: bridge